title: CompArch Mentoring

logo: /assets/img/logo.jpg
title-below-logo: true

description:
show_downloads: false
theme: jekyll-theme-minimal

include:
  - pages

colors:
  theme: t2274a5
  theme-light: 54b4eb
